### PR TITLE
[lipstick] fix notificationmanager tests. Contributes to MER#995

### PR DESCRIPTION
**Pull request by rainisto**
"PRAGMA user_version" was introduced in https://github.com/nemomobile/lipstick/commit/a17e75ef70be1d0781d64693fd8ebeb2f1b009ff#diff-931eed97b16c83a3322270908332ff1cR615 but someone forgot to update the tests.

### CODE REVIEW

**Comment by mikkoharju** [comment]
lgtm

**Comment by rainisto** [comment]
feel free to merge, I dont have write access to this repo.

**Comment by matthewvogt** [comment]
I broke this, and subsequently fixed it in https://github.com/nemomobile/lipstick/pull/306 , so I am confused as to why this does not show as conflicting...

**Comment by rainisto** [comment]
Yep seems that github is buggy somehow, maybe it only checks the time when the pull request is made. Anyways as fix is already merged, then this can be rejected.

**Pull request closed without merging**
