### PR TITLE
[lipstick] Force normal composition when we get SHM buffers. Fixes JB#31162.

### PR DESCRIPTION
**Pull request by sletta**

### CODE REVIEW

**Comment by adenexter** [comment]
I can't reproduce the crash with this applied, I am however seeing some black frames where I think it would have crashed before.  Still, not crashing so LGTM.

**Comment by adenexter** [comment]
Actually, the black frames were visible in the cover as well so they won't be related to this. So all good then.

**Comment by sledges** [comment]
yoohoo!

**Comment by sletta** [comment]
Yeah, I noticed black frames also before I started working on this, so it is unrelated.

**Comment by adenexter** [comment]
Dammit, I didn't test any regular applications.  And they crash now.

#0  0xf77c3440 in ?? ()
#1  0xecfbad78 in ?? ()
#2  0xf6178c35 in qt_assert(char const*, char const*, int) () from /usr/lib/libQt5Core.so.5
#3  0xf720341d in QSGGeometry::updateTexturedRectGeometry(QSGGeometry*, QRectF const&, QRectF const&) () from /usr/lib/libQt5Quick.so.5
#4  0xf7213680 in ?? () from /usr/lib/libQt5Quick.so.5
#5  0xf7213946 in QSGSimpleTextureNode::setTexture(QSGTexture*) () from /usr/lib/libQt5Quick.so.5
#6  0xf7096847 in QWaylandSurfaceItem::updatePaintNode(QSGNode*, QQuickItem::UpdatePaintNodeData*) () from /usr/lib/libQt5Compositor.so.5
#7  0xf76e7608 in LipstickCompositorWindow::updatePaintNode (this=0x9153638, old=0xea71a8c8, data=0x873f0d0) at compositor/lipstickcompositorwindow.cpp:486
#8  0xf726ee4e in QQuickWindowPrivate::updateDirtyNode(QQuickItem*) () from /usr/lib/libQt5Quick.so.5
#9  0xf726f4d7 in QQuickWindowPrivate::updateDirtyNodes() () from /usr/lib/libQt5Quick.so.5
#10 0xf726f563 in QQuickWindowPrivate::syncSceneGraph() () from /usr/lib/libQt5Quick.so.5

**Pull request merged**
