### PR TITLE
[lipstick] Set the correct DBus interface for the WindowModel

### PR DESCRIPTION
**Pull request by giucam**

### CODE REVIEW

**Comment by thp** [comment]
LGTM.

**Comment by mikkoharju** [comment]
Unrelated, but WindowModel is not a singleton (and actually encourages inheriting with its virtual approveWindow() method) but still it registers itself with constant dbus path. What happens if/when multiple windowmodels are created for different purposes?

**Comment by mikkoharju** [comment]
LGTM

**Comment by giucam** [comment]
@mikkoharju I suppose the second registerObject() call will fails. Its docs say "This function does not replace existing objects: if there is already an object registered at path path, this function will return false. Use unregisterObject() to unregister it first."
Same thing with registerService().

**Pull request merged**
