### PR TITLE
Add a wayland interface to record the screen

### PR DESCRIPTION
**Pull request by giucam**
This PR adds a protocol allowing an external client to ask lipstick to record and pass frames to it. The client can then save them to file, send them remotely, make a video...
There are a couple of open questions still: should we restrict the lipstick_recorder global to only some clients? If so, how? Should we show something on screen when it's recording?

### CODE REVIEW

**Comment by giucam** [comment]
ping

**Comment by giucam** [comment]
This is getting quite old. If there are no objections i'd merge it in a few days.

**Comment by d0b3rm4n** [comment]
I can confirm the code works for the mervncserver (https://github.com/mer-qa/mervncserver/tree/lipstick-recorder), and with latest commit 42ca511 the mervncserver must run in group 'privileged' in order to get frames. From my POV LGTM, but from code POV I can't comment.

**Comment by special** [comment]
LGTM from the security perspective, can't comment on the wayland side.

**Pull request merged**
